FROM nginx:alpine

# Remove default nginx config if it exists as a file or directory
RUN rm -rf /etc/nginx/nginx.conf

# Copy custom nginx config
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
